# Generated by Django 4.0.1 on 2022-06-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.TextField(max_length=100)),
                ('lname', models.TextField(max_length=100)),
                ('blood', models.TextField(max_length=100)),
                ('aadhaar', models.TextField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('dob', models.TextField(max_length=100)),
                ('gender', models.TextField(max_length=100)),
                ('address', models.TextField(max_length=100)),
                ('state', models.TextField(max_length=100)),
                ('district', models.TextField(max_length=100)),
                ('pin', models.TextField(max_length=100)),
                ('phone', models.TextField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.TextField(max_length=100)),
                ('cpassword', models.TextField(max_length=100)),
            ],
            options={
                'db_table': 'donor',
            },
        ),
    ]
