# Generated by Django 4.0.1 on 2022-06-13 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signupapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donor',
        ),
    ]
