# Generated by Django 4.0.1 on 2022-07-01 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signupapp', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donor',
        ),
    ]
