# Generated by Django 4.0.1 on 2022-07-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupapp', '0006_remove_donors_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donors',
            name='phone',
            field=models.IntegerField(max_length=100),
        ),
    ]
