# Generated by Django 4.0.1 on 2022-07-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupapp', '0007_alter_donors_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donors',
            name='phone',
            field=models.TextField(max_length=100),
        ),
    ]
