# Generated by Django 4.0.1 on 2022-07-01 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signupapp', '0008_alter_donors_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donors',
            old_name='day',
            new_name='dob',
        ),
        migrations.RemoveField(
            model_name='donors',
            name='month',
        ),
        migrations.RemoveField(
            model_name='donors',
            name='year',
        ),
    ]
