# Generated by Django 4.0.1 on 2022-07-01 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signupapp', '0009_rename_day_donors_dob_remove_donors_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donors',
            name='dob',
        ),
    ]
