# Generated by Django 4.0.1 on 2022-07-01 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signupapp', '0010_remove_donors_dob'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donors',
        ),
    ]
