# Generated by Django 4.0.1 on 2022-07-02 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signupapp', '0012_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donors',
            old_name='auth',
            new_name='authentication',
        ),
    ]
