# Generated by Django 4.0.1 on 2022-07-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupapp', '0014_recipients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hname', models.TextField(max_length=100)),
                ('address', models.TextField(max_length=100)),
                ('location', models.TextField(max_length=100)),
                ('state', models.TextField(max_length=100)),
                ('district', models.TextField(max_length=100)),
                ('pin', models.TextField(max_length=100)),
                ('phone', models.TextField(max_length=100)),
                ('email', models.TextField(max_length=100)),
                ('password', models.TextField(max_length=100)),
                ('cpassword', models.TextField(max_length=100)),
                ('authentication', models.TextField(max_length=50)),
            ],
            options={
                'db_table': 'hospitaldetails',
            },
        ),
        migrations.AlterField(
            model_name='recipients',
            name='authentication',
            field=models.TextField(max_length=50),
        ),
    ]
