# Generated by Django 4.0.1 on 2022-05-13 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipientapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blood',
            table='recipientbloodrequest',
        ),
    ]
