# Generated by Django 4.0.1 on 2022-06-13 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipientapp', '0002_alter_blood_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blood',
            table='bloodrequest',
        ),
    ]
