# Generated by Django 4.0.1 on 2022-06-13 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donorapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blood',
        ),
    ]
