# Generated by Django 4.0.1 on 2022-09-23 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donorapp', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kvkapositive',
        ),
    ]
