# Generated by Django 4.0.1 on 2022-09-23 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donorapp', '0004_delete_kvkapositive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Karuvarakundu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('blood', models.TextField(max_length=50)),
                ('address', models.TextField(max_length=50)),
                ('email', models.TextField(max_length=50)),
                ('phone', models.TextField(max_length=50)),
            ],
            options={
                'db_table': 'kvk_donors',
            },
        ),
    ]
