# Generated by Django 4.0.1 on 2022-09-23 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donorapp', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Karuvarakundu',
        ),
    ]
