# Generated by Django 4.0.1 on 2022-05-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood', models.TextField(max_length=20)),
                ('name', models.TextField(max_length=20)),
                ('phone', models.TextField(max_length=20)),
                ('location', models.TextField(max_length=20)),
            ],
            options={
                'db_table': 'hospitalbloodrequest',
            },
        ),
    ]
