# Generated by Django 4.0.1 on 2022-06-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizer', models.TextField(max_length=100)),
                ('date', models.TextField(max_length=100)),
                ('address', models.TextField(max_length=100)),
                ('state', models.TextField(max_length=100)),
                ('district', models.TextField(max_length=100)),
                ('name', models.TextField(max_length=100)),
                ('phone', models.TextField(max_length=100)),
                ('email', models.TextField(max_length=100)),
            ],
            options={
                'db_table': 'camps',
            },
        ),
    ]
