# Generated by Django 4.0.1 on 2022-06-13 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0002_camps'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camps',
            old_name='organizer',
            new_name='camp',
        ),
    ]
