# Generated by Django 4.0.1 on 2022-06-13 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0004_alter_camps_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blood',
        ),
    ]
