# Generated by Django 4.0.1 on 2022-09-14 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=25)),
                ('email', models.TextField(max_length=25)),
                ('message', models.TextField(max_length=100)),
            ],
        ),
    ]
