# Generated by Django 4.0.1 on 2022-09-14 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainhomeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contact',
            table='contact_details',
        ),
    ]
