# Generated by Django 4.0.1 on 2022-09-14 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainhomeapp', '0002_alter_contact_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
