# Generated by Django 4.0.1 on 2022-09-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainhomeapp', '0003_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=25)),
                ('email', models.TextField(max_length=25)),
                ('message', models.TextField(max_length=50)),
            ],
            options={
                'db_table': 'contact_details',
            },
        ),
    ]
