# Generated by Django 4.0.1 on 2022-09-14 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainhomeapp', '0004_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='cname',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='emailid',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='message',
            new_name='messages',
        ),
    ]
