# Generated by Django 4.0.1 on 2022-09-14 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainhomeapp', '0005_rename_email_contact_cname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='cname',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='messages',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='emailid',
            new_name='name',
        ),
        migrations.AlterModelTable(
            name='contact',
            table='contact_data',
        ),
    ]
