from django.urls import path
from.import views

urlpatterns = [
    path('hospital', views.hospital, name="hospital_home"),
    path('hospitalsearch', views.hospitalsearch, name="hospital_search"),
    path('hospitalcamp', views.hospitalcamp, name='hospitalcamp'),
    path('camptable', views.camptable, name="camptable"),
    path('camp_details', views.camp_details, name = 'camp_details'),
    path('camp', views.camp, name = 'camp'),
    path('camp_update<int:id>', views.camp_update, name = 'camp_update'),
    path('camp_delete<int:id>', views.camp_delete, name = 'camp_delete'),
    path('kvk_aplus', views.kvk_aplus),
    path('kvk_aminus', views.kvk_aminus),
    path('kvk_bplus', views.kvk_bplus),
    path('kvk_bminus', views.kvk_bminus),
    path('kvk_oplus', views.kvk_oplus),
    path('kvk_ominus', views.kvk_ominus),
    path('kvk_abplus', views.kvk_abplus),
    path('kvk_abminus', views.kvk_abminus),
    path('manjeri_aplus', views.manjeri_aplus),
    path('manjeri_aminus', views.manjeri_aminus),
    path('manjeri_bplus', views.manjeri_bplus),
    path('manjeri_bminus', views.manjeri_bminus),
    path('manjeri_oplus', views.manjeri_oplus),
    path('manjeri_ominus', views.manjeri_ominus),
    path('manjeri_abplus', views.manjeri_abplus),
    path('manjeri_abminus', views.manjeri_abminus),
    path('mal_aplus', views.mal_aplus),
    path('mal_aminus', views.mal_aminus),
    path('mal_bplus', views.mal_bplus),
    path('mal_bminus', views.mal_bminus),
    path('mal_oplus', views.mal_oplus),
    path('mal_ominus', views.mal_ominus),
    path('mal_abplus', views.mal_abplus),
    path('mal_abminus', views.mal_abminus),
    path('w_aplus', views.w_aplus),
    path('w_aminus', views.w_aminus),
    path('w_bplus', views.w_bplus),
    path('w_bminus', views.w_bminus),
    path('w_oplus', views.w_oplus),
    path('w_ominus', views.w_ominus),
    path('w_abplus', views.w_abplus),
    path('w_abminus', views.w_abminus),
    path('n_aplus', views.n_aplus),
    path('n_aminus', views.n_aminus),
    path('n_bplus', views.n_bplus),
    path('n_bminus', views.n_bminus),
    path('n_oplus', views.n_oplus),
    path('n_ominus', views.n_ominus),
    path('n_abplus', views.n_abplus),
    path('n_abminus', views.n_abminus),
    path('v_aplus', views.v_aplus),
    path('v_aminus', views.v_aminus),
    path('v_bplus', views.v_bplus),
    path('v_bminus', views.v_bminus),
    path('v_oplus', views.v_oplus),
    path('v_ominus', views.v_ominus),
    path('v_abplus', views.v_abplus),
    path('v_abminus', views.v_abminus),
]