# Generated by Django 4.0.1 on 2022-07-06 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_donors_hospitals_recipients'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donors',
        ),
        migrations.DeleteModel(
            name='Hospitals',
        ),
        migrations.DeleteModel(
            name='Recipients',
        ),
    ]
