# Generated by Django 4.0.1 on 2022-07-06 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0008_donor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Donor',
            new_name='Donors',
        ),
    ]
