# Generated by Django 4.0.1 on 2022-07-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0010_recipients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hname', models.TextField(max_length=50)),
                ('address', models.TextField(max_length=50)),
                ('location', models.TextField(max_length=50)),
                ('state', models.TextField(max_length=50)),
                ('district', models.TextField(max_length=50)),
                ('pin', models.TextField(max_length=50)),
                ('phone', models.TextField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.TextField(max_length=50)),
                ('cpassword', models.TextField(max_length=50)),
                ('authentication', models.TextField(max_length=50)),
            ],
            options={
                'db_table': 'hospital_details',
            },
        ),
    ]
